### ISSUE TITLE
Unable to save Gif from URL

### ISSUE THREAD

**Issue by danielwrobert** [chad1008/Gifomattic#5]
I may be doing something wrong here but when I try to add a gif by the URL via the `gifadd` command, Alfred tries to run a search query. For example, `gifadd http://i.makeagif.com/media/5-19-2015/F35uZ2.gif` will pop open a browser tab with the [following result](https://www.google.com/search?q=gifadd+http%3A%2F%2Fi.makeagif.com%2Fmedia%2F5-19-2015%2FF35uZ2.gif).

Additionally, I attempted to set a hotkey shortcut. This does pop open Alfred with the URL pre-populated but it does not allow me to hit `return` to actually save the gif.

I tried this with a couple of URLs and even saved a gif to Cloudup. All returned the same result.

I'm using Alfred v3.1.1[737] on a MacBook Pro (latest).

**Comment by chad1008** [comment]
Thanks @danielwrobert! Definitely not anything you did. When I first set up Gifomattic, I was using the Workflows.php library: https://github.com/jdfwarrior/Workflows/blob/master/workflows.php

That was later removed during the migration to Alfred 3, which also took away the behind the scenes creation of the workflow's data folder. Without that folder, the database can't be created, which breaks all the things.

Getting a fix uploaded shortly :)

**Comment by chad1008** [comment]
Should be fixed by 9a0dcc2 - @danielwrobert if you re-install do are you able to save a gif?

**Comment by danielwrobert** [comment]
Yup, I re-installed it and everything's working as expected. Thanks for fixing that!

This is a cool workflow, I'm excited to start using it!! :)

**Comment by chad1008** [comment]
Ha, thanks for being Gifomattic's first official user ;) (That kind of makes you involuntary tester as well, sorry!)
